In [6]:
! pip install imbalanced-learn

In [3]:
import pandas as pd

df = pd.read_csv("../../data/processed/cleaned_data.csv",dtype="category")
df.head()

Route Type     Collision Type Weather Surface Condition           Light  \
0        County              OTHER   CLEAR               DRY        DAYLIGHT   
1        County              OTHER  CLOUDY               DRY        DAYLIGHT   
2  Municipality  SAME DIR REAR END   CLEAR               DRY            DAWN   
3        County     SINGLE VEHICLE  CLOUDY               DRY        DAYLIGHT   
4        County     SINGLE VEHICLE   CLEAR               DRY  DARK LIGHTS ON   

  Traffic Control Driver Substance Abuse Driver At Fault Injury Severity  \
0     NO CONTROLS               DETECTED             Yes       No Injury   
1     NO CONTROLS          NONE DETECTED             Yes    Minor Injury   
2  TRAFFIC SIGNAL          NONE DETECTED              No       No Injury   
3     NO CONTROLS          NONE DETECTED              No       No Injury   
4     NO CONTROLS               DETECTED              No       No Injury   

  Driver Distracted By Speed Limit Day of Week Time of Day  
0       NOT DISTRACTED       15-25      Sunday   afternoon  
1       NOT DISTRACTED       15-25      Monday     morning  
2       NOT DISTRACTED       30-40     Tuesday     morning  
3       NOT DISTRACTED       30-40     Tuesday     morning  
4       NOT DISTRACTED       30-40    Thursday        dawn

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105379 entries, 0 to 105378
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype   
---  ------                  --------------   -----   
 0   Route Type              105379 non-null  category
 1   Collision Type          105379 non-null  category
 2   Weather                 105379 non-null  category
 3   Surface Condition       105379 non-null  category
 4   Light                   105379 non-null  category
 5   Traffic Control         105379 non-null  category
 6   Driver Substance Abuse  105379 non-null  category
 7   Driver At Fault         105379 non-null  category
 8   Injury Severity         105379 non-null  category
 9   Driver Distracted By    105379 non-null  category
 10  Speed Limit             105379 non-null  category
 11  Day of Week             105379 non-null  category
 12  Time of Day             105379 non-null  category
dtypes: category(13)
memory usage: 1.3 MB


In [1]:
# Random Forest can be utilized for feature selection by leveraging the feature importance scores provided by the algorithm

import sklearn
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [4]:
rf = RandomForestClassifier()
df_numeric = df.apply(lambda x: x.cat.codes)
y=df_numeric["Injury Severity"]
x=df_numeric.drop(["Injury Severity"],axis=1)
rf.fit(x, y)

RandomForestClassifier()

In [5]:
importance = rf.feature_importances_
indices = np.argsort(importance)[::-1]  # Sort indices in descending order
for i, feature_index in enumerate(indices):
    print(f"Feature {i+1}: {x.columns[feature_index]} ({importance[feature_index]})")

Feature 1: Day of Week (0.2413110611051155)
Feature 2: Collision Type (0.17156239100919168)
Feature 3: Route Type (0.09834265420188883)
Feature 4: Time of Day (0.08500256727808762)
Feature 5: Light (0.07988932601527288)
Feature 6: Weather (0.07533660754895521)
Feature 7: Traffic Control (0.074082242567594)
Feature 8: Speed Limit (0.051841030568435906)
Feature 9: Surface Condition (0.035316691660599225)
Feature 10: Driver Substance Abuse (0.0340219788984097)
Feature 11: Driver At Fault (0.03034005191000452)
Feature 12: Driver Distracted By (0.02295339723644496)


In [17]:
# balance class attribute data
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

x, y = make_classification(n_samples=105379,  # Same as the number of rows in your DataFrame
    n_features=12,  # Total number of features excluding the class attribute
    n_informative=12,  # Number of informative features in your dataset
    n_redundant=0,  # Number of redundant features (adjust as needed)
    n_repeated=0,  # Number of repeated features (adjust as needed)
    n_classes=3,  # Number of classes in your class attribute
    weights=[84376, 19981, 1022],  # Class distribution of the target variable
    random_state=42)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [18]:
# SMOTE

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)

print("Before SMOTE:")
print(np.bincount(y_train))

print("After SMOTE:")
print(np.bincount(y_train_resampled))

Before SMOTE:
[83763   285   255]
After SMOTE:
[83763 83763 83763]


In [19]:
# ROSE

from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
x_train_resampled, y_train_resampled = ros.fit_resample(x_train, y_train)

print("Before ROSE:")
print(np.bincount(y_train))

print("After ROSE:")
print(np.bincount(y_train_resampled))

Before ROSE:
[83763   285   255]
After ROSE:
[83763 83763 83763]


In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105379 entries, 0 to 105378
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype   
---  ------                  --------------   -----   
 0   Route Type              105379 non-null  category
 1   Collision Type          105379 non-null  category
 2   Weather                 105379 non-null  category
 3   Surface Condition       105379 non-null  category
 4   Light                   105379 non-null  category
 5   Traffic Control         105379 non-null  category
 6   Driver Substance Abuse  105379 non-null  category
 7   Driver At Fault         105379 non-null  category
 8   Injury Severity         105379 non-null  category
 9   Driver Distracted By    105379 non-null  category
 10  Speed Limit             105379 non-null  category
 11  Day of Week             105379 non-null  category
 12  Time of Day             105379 non-null  category
dtypes: category(13)
memory usage: 1.3 MB
